- name: Get the default target of the remote host
  command:
    argv:
      - systemctl
      - get-default
  register: default_target

- name: Template the service file out to the remote host
  become: true
  become_user: root
  become_method: su
  template:
    owner: root
    group: root
    mode: 0644
    src: clash.service.j2
    dest: /etc/systemd/system/clash_{{ ansible_ssh_user }}.service

- name: Autostart clash service at startup
  become: true
  become_user: root
  become_method: su
  systemd_service:
    name: clash_{{ ansible_ssh_user }}
    daemon_reload: true
    state: started
    enabled: true
